version: "3.4"

services:
  sawaspace:
    image: registry.gitlab.com/z81/dgf:latest
    ports:
      - "6860:80"

    labels:
      - "traefik.frontend.rule=Host:dgf.sawa.space"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure