version: "3.4"

services:
  sawaspace:
    image: registry.gitlab.com/z81/dgf:latest
    ports:
      - "6850:80"

    labels:
      - "traefik.frontend.rule=Path:/"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure