apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dgf
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dgf
    template:
        metadata:
            labels:
                app: dgf
        spec:
            containers:
                - name: dgf
                  image: registry.gitlab.com/z81/sawa.space
                  ports:
                      - containerPort: 80
